apps/posts/urls.py
from django.urls import path
from .views import *


app_name = 'posts'

urlpatterns = [
    # Posts
    path('', PostListView.as_view(), name='index'),
    path('v/<slug:slug>', PostDetailView.as_view(), name='view'),
    path('create/', PostCreateView.as_view(), name='create'),
    path('<slug:slug>/delete', PostDeleteView.as_view(), name='delete'),
    path('<slug:slug>/update', PostUpdateView.as_view(), name='update'),
    path('<slug:slug>/like', like_post, name='like'),

    # Comments
    path('<slug:slug>/comment', PostCommentCreateView.as_view(), name='add_comment'),
    path('<slug:slug>/comment/<uuid:cpk>/delete',
         PostCommentDeleteView.as_view(), name='delete_comment'),
    path('<slug:slug>/comment/<uuid:cpk>/update',
         PostCommentUpdateView.as_view(), name='update_comment'),

    # Categories
    path('category/create', PostCategoryCreateView.as_view(), name='create_category'),
    path('category/<slug:slug>/update',
         PostCategoryUpdateView.as_view(), name='update_category'),
    path('category/<slug:slug>/delete',
         PostCategoryDeleteView.as_view(), name='delete_category'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.error_handling.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('apps.sections.urls')),
    path('posts/', include('apps.posts.urls')),
    path('', include('apps.users.urls')),
    path('contacts/', include('apps.contacts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = custom_access_denied
handler404 = custom_page_not_found

apps/comments/models.py
from django.db import models
from django.contrib.auth import get_user_model
from apps.posts.models import Post
from django.urls import reverse

import uuid

class PostComment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    text = models.TextField(max_length=300, verbose_name="Contenido del comentario")
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, verbose_name="Articulo al que pertenece"
    )
    author = models.ForeignKey(
        get_user_model(),
        null=True,
        on_delete=models.SET_NULL,
        verbose_name="Autor del comentario",
    )
    created_at = models.DateTimeField(
        auto_now_add=True, editable=False, verbose_name="Fecha de creación"
    )
    updated_at = models.DateTimeField(
        auto_now=True, editable=False, verbose_name="Fecha de actualización"
    )
    edited = models.BooleanField(default=False, verbose_name="Fue editado?")
    likes = models.ManyToManyField(
        get_user_model(), blank=True, related_name="liked_comments"
    )

    class Meta:
        verbose_name = "Comentario"
        verbose_name_plural = "Comentarios"
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return f"{self.author.username}: {self.text[:50]}"

    def get_delete_url(self):
        return reverse("posts:delete_comment", args=[self.post.slug, self.pk])

    def get_update_url(self):
        return reverse("posts:update_comment", args=[self.post.slug, self.pk])

apps/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(
        max_length=100, verbose_name="Nombre de la categoría")
    slug = models.SlugField(unique=True)
    created_at = models.DateTimeField(
        auto_now_add=True, editable=False, verbose_name="Fecha de creación"
    )
    updated_at = models.DateTimeField(
        auto_now=True, editable=False, verbose_name="Fecha de actualización"
    )

    class Meta:
        verbose_name = "Categoría"
        verbose_name_plural = "Categorías"

    def __str__(self) -> str:
        return self.name

    def get_filterby_link(self):
        url = reverse("posts:index")
        return f"{url}?category={self.slug}"

    def get_update_url(self):
        return reverse('posts:update_category', args=[self.slug])

    def get_delete_url(self):
        return reverse('posts:delete_category', args=[self.slug])


class Tag(models.Model):
    name = models.CharField(
        max_length=100, verbose_name="Nombre de la etiqueta")
    created_at = models.DateTimeField(
        auto_now_add=True, editable=False, verbose_name="Fecha de creación"
    )
    updated_at = models.DateTimeField(
        auto_now=True, editable=False, verbose_name="Fecha de actualización"
    )

    class Meta:
        verbose_name = "Etiqueta"
        verbose_name_plural = "Etiquetas"

    def __str__(self) -> str:
        return f"#{self.name}"


class Post(models.Model):
    slug = models.SlugField(unique=True)
    title = models.CharField(
        max_length=100,
        verbose_name="Título del Artículo",
        help_text="Escribe el titulo del artículo",
    )
    short_description = models.TextField(
        max_length=750,
        verbose_name="Descripción breve o resumen",
        help_text="Escribe una breve descripcion o resumen del artículo",
    )
    image = models.ImageField(
        upload_to='posts',
        null=True,
        blank=True,
        verbose_name="Imagen relacionada",
        help_text="Selecciona una imagen relacionada para mostrar como portada del artículo",
    )
    content = models.TextField(
        verbose_name="Contenido del artículo",
        help_text="Escribe el contenido del artículo",
    )
    created_at = models.DateTimeField(
        auto_now_add=True, editable=False, verbose_name="Fecha de creación"
    )
    updated_at = models.DateTimeField(
        auto_now=True, editable=False, verbose_name="Fecha de actualización"
    )
    author = models.ForeignKey(
        get_user_model(),
        null=True,
        on_delete=models.SET_NULL,
        verbose_name="Autor del artículo",
    )
    category = models.ForeignKey(
        Category,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name="Categoría a la que pertenece",
    )
    tags = models.ManyToManyField(
        Tag, verbose_name="Etiquetas relacionadas", blank=True
    )
    likes = models.ManyToManyField(
        get_user_model(), blank=True, related_name="liked_posts"
    )
    views = models.IntegerField(default=0)

    class Meta:
        verbose_name = "Artículo"
        verbose_name_plural = "Artículos"

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse("posts:view", args=[self.slug])

    def get_delete_url(self):
        return reverse("posts:delete", args=[self.slug])

    def get_update_url(self):
        return reverse("posts:update", args=[self.slug])

    def get_add_comment_url(self):
        return reverse("posts:add_comment", args=[self.slug])

    def get_like_url(self):
        return reverse("posts:like", args=[self.slug])

apps/posts/forms.py
from django import forms
from .models import *

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        exclude = ['created_at', 'updated_at', 'likes', 'author', 'views']

class CategoryForm(forms.ModelForm):
    
    class Meta:
        model = Category
        fields = '__all__'

apps/posts/views.py
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView,
    FormView,
)
from .models import *
from .forms import *
from django.urls import reverse_lazy
from apps.comments.forms import *
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect


class PostListView(ListView):
    model = Post
    template_name = "posts/post_list.html"
    context_object_name = "posts"

    def get_queryset(self):
        queryset = Post.objects.all().order_by("-created_at")

        category = self.request.GET.get("category", "")
        q = self.request.GET.get("q", "")

        if category:
            queryset = queryset.filter(Q(category__slug=category))

        if q:
            qset = (
                Q(title__icontains=q)
                | Q(author__first_name__icontains=q)
                | Q(category__name__icontains=q)
            )

            queryset = queryset.filter(qset)

        return queryset


class PostDetailView(DetailView):
    model = Post
    template_name = "posts/post_detail.html"
    context_object_name = "post"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["postcomment_form"] = PostCommentForm()
        return context

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        post = self.get_object()
        visited = self.request.COOKIES.get('visited_' + str(post.slug))

        if not visited:

            post.views += 1
            post.save()
            response.set_cookie('visited_' + str(post.slug), 'true')

        return response


class PostCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    template_name = "posts/post_create.html"
    form_class = PostForm

    def test_func(self):
        return self.request.user.is_staff

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = "posts/post_delete.html"
    success_url = reverse_lazy("posts:index")

    def test_func(self):
        return self.request.user.is_staff


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = "posts/post_update.html"
    success_url = reverse_lazy("posts:index")
    form_class = PostForm

    def test_func(self):
        return self.request.user.is_staff


class PostCommentCreateView(LoginRequiredMixin, FormView):
    form_class = PostCommentForm
    template_name = "posts/post_detail.html"

    def form_valid(self, form):
        post = Post.objects.get(slug=self.kwargs["slug"])
        comment = form.save(commit=False)
        comment.author = self.request.user
        comment.post = post
        comment.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse("posts:view", args=[self.kwargs["slug"]])


class PostCommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = PostComment
    template_name = "posts/comments/delete.html"
    pk_url_kwarg = "cpk"

    def get_success_url(self):
        return reverse("posts:view", args=[self.kwargs["slug"]])

    def test_func(self):
        cpk = self.kwargs["cpk"]
        comment = PostComment.objects.get(pk=cpk)
        return self.request.user == comment.author or self.request.user.is_staff


class PostCommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = PostComment
    template_name = "posts/comments/update.html"
    form_class = PostCommentForm
    pk_url_kwarg = "cpk"

    def get_success_url(self):
        return reverse("posts:view", args=[self.kwargs["slug"]])

    def test_func(self):
        cpk = self.kwargs["cpk"]
        comment = PostComment.objects.get(pk=cpk)
        return self.request.user == comment.author


@login_required
def like_post(request, slug):
    if request.method == "POST":
        post = Post.objects.get(slug=slug)
        if request.user in post.likes.all():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)
    return redirect("posts:view", slug)


class PostCategoryCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Category
    template_name = 'posts/categories/create.html'
    form_class = CategoryForm
    success_url = reverse_lazy('posts:index')

    def test_func(self):
        return self.request.user.is_staff


class PostCategoryUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Category
    template_name = 'posts/categories/update.html'
    form_class = CategoryForm
    success_url = reverse_lazy('posts:index')

    def test_func(self):
        return self.request.user.is_staff


class PostCategoryDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Category
    template_name = "posts/categories/delete.html"
    success_url = reverse_lazy('posts:index')

    def test_func(self):
        return self.request.user.is_staff

templates/posts/editor.html
<script src="https://cdn.jsdelivr.net/npm/sceditor@3/minified/formats/bbcode.min.js"></script>
<script>
    var textarea = document.getElementById('id_content');
    sceditor.create(textarea, {
        format: 'html',
        style: 'https://cdn.jsdelivr.net/npm/sceditor@3/minified/themes/content/default.min.css',
        
    });
</script>

templates/posts/post_card.html
<article class="card  my-3">
    <div class="card-body">
        <h2 class="mt-5">{{post.title}}</h2>
        <p>{{post.short_description}}</p>
        <p>By <a href="{{post.author.get_absolute_url}}"><b>{% if post.author %}{{post.author}}{% else %} Anónimo {% endif %}</b></a> in <a href="{{post.category.get_filterby_link}}"><b>
                        {% if post.category %}{{post.category}}{% else %} Sin categoría {% endif %}</b></a> - <span
                class="bi {% if user in post.likes.all %}bi-heart-fill text-danger{% else %}bi-heart{%endif%}">{{post.likes.all|length}}</span>
            - <span>Veces abierto: {{post.views}}</span>
            - <span>Comentarios: {{post.postcomment_set.all|length}}</span>
        </p>
        <hr>
        <a class="btn btn-primary" href="{{post.get_absolute_url}}">Ver detalles</a>
        {% if user.is_staff %}
        <a class="btn btn-secondary" href="{{post.get_update_url}}">Actualizar</a>
        <a class="btn btn-danger" href="{{post.get_delete_url}}">Eliminar</a>
        {% endif %}
    </div>
</article>

templates/posts/post_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Crear nuevo articulo
{% endblock title %}

{% block content %}
<main class="container">
    <h1 class="mt-5">Crear nuevo articulo</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <p><button class="btn btn-success" type="submit">Crear Publicación</button> <a class="btn btn-secondary"
                href="{% url 'posts:index' %}">Cancelar</a></p>
    </form>
</main>
{% include 'posts/editor.html' %}
{% endblock content %}

templates/posts/post_delete.html
{% extends 'base.html' %}
{% block title %}
Confirmar eliminacion de {{post.title}}
{% endblock title %}
{% block content %}
<main class="container">
    <div class="card mt-5">
        <div class="card-header">
            <h1>Confirmar eliminacion de articulo</h1>
        </div>
        <form class="card-body" action="" method="POST">
            {% csrf_token %}
            <h5 class="lead">
                Estás seguro de que deseas borrar el articulo: "{{post}}"?
            </h5>
            <p><button class="btn btn-danger" type="submit">Confirmar</button> <a class="btn btn-secondary"
                    href="{% url 'posts:index' %}">Cancelar</a></p>
        </form>
    </div>
</main>
{% endblock content %}

templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
{{post.title}}
{% endblock title %}

{% block content %}
<main class="container">
    <div class="my-2">
        <a href="{% url 'index' %}">Blog</a> &gt; <a href="{% url 'posts:index' %}">Artículos</a> &gt; <a
            href="{{post.category.get_filterby_link}}">{{post.category}}</a> &gt; <span>{{post.title}}</span>
    </div>
    <h1 class="mt-5">{{post.title}}</h1>
    <b>{{post.author.username}} | {{post.created_at}} | {{post.updated_at}}</b>
    <p>{{post.short_description}}</p>
    {% if post.image %}
    <img class="img-fluid" src="{{post.image.url}}" alt="{{post.title}}">
    {% endif %}
    <p>{{post.content|safe}}</p>
    {% include 'posts/post_likes.html' %}
    {% include 'posts/comments/list.html' %}
    {% include 'posts/comments/form.html' %}
</main>
{% endblock content %}

templates/posts/post_likes.html
<div>
    {% if user in post.likes.all %}
    <h5><i>Has indicado que te gusta este artículo</i></h5>
    {% endif %}
    <form action="{{post.get_like_url}}" method="POST">
        {% csrf_token %}
        <button class="btn bi {% if user in post.likes.all %}bi-heart-fill text-danger{% else %}bi-heart{%endif%}"
            type="submit"> {{post.likes.all|length}}</button>
    </form>
</div>

templates/posts/post_list.html
{% extends 'base.html' %}
{% block title %} Articulos {% endblock title %}
{% block content %}
<main class="d-flex">
    {% include 'posts/sidebar.html' %}
    <section class="container">
        {% if user.is_staff %}
        <a class="btn btn-success my-3" href="{% url 'posts:create' %}"><i class="fa-solid fa-plus"></i> Nueva
            Publicación</a>
        {% endif %}
        {% if request.GET.q %}
        <h1>Resultados para: {{request.GET.q}}</h1>
        {% elif request.GET.category %}
        <h1>Artículos en: {{request.GET.category}}</h1>
        {% endif %}
        {% for post in posts %}
        {% include 'posts/post_card.html' %}
        {% empty %}
        {% if request.GET.q %}
        <h2>No hay resultados para "{{request.GET.q}}"</h2>
        {% elif request.GET.category %}
        <h2>No hay articulos en categoría "{{request.GET.category}}"</h2>
        {% else %}
        <h2>No hay articulos para mostrar</h2>
        {% endif %}
        {% endfor %}
    </section>
</main>
{% endblock content %}

templates/posts/post_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
{{post.title}} - Actualizar
{% endblock title %}
{% block content %}
<main class="container">
    <h1 class="mt-5">Actualizar articulo: {{post.title}}</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <p>
            <button class="btn btn-success" type="submit">Actualizar Publicación</button>
            <a class="btn btn-secondary" href="{% url 'posts:index' %}">Cancelar</a>
        </p>
    </form>
</main>
{% include 'posts/editor.html' %}
{% endblock content %}

templates/posts/sidebar.html
<aside class="bd-sidebar">
    <nav class="collapse bd-links" id="bd-docs-nav" aria-label="Docs navigation">
        <ul class="list-unstyled mb-0 py-3 pt-md-1">
            <li class="mb-1">
                <button class="btn d-inline-flex align-items-center rounded" data-bs-toggle="collapse"
                    data-bs-target="#collapse1" aria-expanded="true">
                    Categorías
                </button>

                <div class="collapse show" id="collapse1">
                    <ul class="list-unstyled fw-normal pb-1 small">
                        {% if user.is_staff %}
                        <li>
                            <a class="d-inline-flex align-items-center rounded"
                                href="{% url 'posts:create_category' %}"><i class="fa-solid fa-plus"></i> Nueva
                                Categoría</a>
                        </li>
                        {% endif %}
                        <li><a href="{% url 'posts:index' %}" class="d-inline-flex align-items-center rounded">Todos los
                                articulos</a></li>
                        {% for category in categories %}
                        <li>
                            <a href="{{category.get_filterby_link}}"
                                class="d-inline-flex align-items-center rounded">{{category.name}}</a>
                            {% if user.is_staff %}
                            <a class="text-secondary" href="{{category.get_update_url}}"><i
                                    class="fa-solid fa-pen-to-square"></i></a>
                            <a class="text-danger" href="{{category.get_delete_url}}"><i class="fa-solid fa-trash"></i></a>
                            {% endif %}
                        </li>
                        {% empty %}
                        No hay categorías
                        {% endfor %}
                    </ul>
                </div>
            </li>
            <li class="mb-1">
                <button class="btn d-inline-flex align-items-center rounded" data-bs-toggle="collapse"
                    data-bs-target="#collapse2" aria-expanded="true">
                    Ordenar por
                </button>

                <div class="collapse show" id="collapse2">
                    <ul class="list-unstyled fw-normal pb-1 small">
                        <li><a href="#" class="d-inline-flex align-items-center rounded">Más reciente</a></li>
                        <li><a href="#" class="d-inline-flex align-items-center rounded">Más destacados</a></li>
                        <li><a href="#" class="d-inline-flex align-items-center rounded">Más antiguos</a></li>
                    </ul>
                </div>
            </li>
        </ul>
    </nav>

</aside>